<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\ProductReceipt;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Chai nhựa HDPE 1 lít xanh',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 1 lít trắng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 1 lít đỏ',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 1 lít vàng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 1 lít đen',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 5 lít xanh',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 5 lít trắng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 5 lít đỏ',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 5 lít vàng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa HDPE 5 lít đen',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 5,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 1 lít đỏ',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 1 lít xanh',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 1 lít vàng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 1 lít trắng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 1 lít đen',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 5 lít đỏ',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 5 lít xanh',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 5 lít vàng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 5 lít trắng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa HDPE 5 lít đen',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 6,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 1 lít đỏ',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 1 lít xanh',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 1 lít vàng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 1 lít trắng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 1 lít đen',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 5 lít đỏ',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 5 lít xanh',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 5 lít vàng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 5 lít trắng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa HDPE 5 lít đen',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 7,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 1 lít xanh',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 1 lít trắng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 1 lít đỏ',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 1 lít vàng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 1 lít đen',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 5 lít xanh',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 5 lít trắng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 5 lít đỏ',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 5 lít vàng',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Chai nhựa PET 5 lít đen',
                'unit' => 'Chai',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 8,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 1 lít đỏ',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 1 lít xanh',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 1 lít vàng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 1 lít trắng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 1 lít đen',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 5 lít đỏ',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 5 lít xanh',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 5 lít vàng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 5 lít trắng',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Xô nhựa PET 5 lít đen',
                'unit' => 'Xô',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 9,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 1 lít đỏ',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 1 lít xanh',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 1 lít vàng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 1 lít trắng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 1 lít đen',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 5 lít đỏ',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 1,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 5 lít xanh',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 2,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 5 lít vàng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 3,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 5 lít trắng',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 4,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'name' => 'Hủ nhựa PET 5 lít đen',
                'unit' => 'Hủ',
                'quantity' => 0,
                'status' => 1,
                'category_id' => 10,
                'color_id' => 5,
                'created_at' => now(),
                'updated_at' => null,
            ],

        ]);
    }
}
