export const STATUS_PROPOSE = {
  PENDING_SEND: 0,
  PEDING_APPROVE: 1,
  APPROVED: 2,
  REJECTED: 3,
};

export const STATUS_INVENTORY_REPORT = {
  PENDING_SEND: 0,
  PEDING_APPROVE: 1,
  APPROVED: 2,
  REJECTED: 3,
};